# Generated by Django 2.1.2 on 2018-10-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='following',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
