# Generated by Django 2.1.2 on 2018-10-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_like_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
    ]
