city_choices = {
	'Adana':'Adana',
	'Adıyaman':'Adıyaman',
	'Afyon':'Afyon',
	'Ağrı':'Ağrı',
	'Amasya':'Amasya',
	'Ankara':'Ankara',
	'Antalya':'Antalya',
	'Artvin':'Artvin',
	'Aydın':'Aydın',
	'Balıkesir':'Balıkesir',
	'Bilecik':'Bilecik',
	'Bingöl':'Bingöl',
	'Bitlis':'Bitlis',
	'Bolu':'Bolu',
	'Burdur':'Burdur',
	'Bursa':'Bursa',
	'Çanakkale':'Çanakkale',
	'Çankırı':'Çankırı',
	'Çorum':'Çorum',
	'Denizli':'Denizli',
	'Diyarbakır':'Diyarbakır',
	'Edirne':'Edirne',
	'Elazığ':'Elazığ',
	'Erzincan':'Erzincan',
	'Erzurum':'Erzurum',
	'Eskişehir':'Eskişehir',
	'Gaziantep':'Gaziantep',
	'Giresun':'Giresun',
	'Gümüşhane':'Gümüşhane',
	'Hakkari':'Hakkari',
	'Hatay':'Hatay',
	'Isparta':'Isparta',
	'İçel (Mersi':'İçel (Mersin)',
	'İstanbul':'İstanbul',
	'İzmir':'İzmir',
	'Kars':'Kars',
	'Kastamonu':'Kastamonu',
	'Kayseri':'Kayseri',
	'Kırklareli':'Kırklareli',
	'Kırşehir':'Kırşehir',
	'Kocaeli':'Kocaeli',
	'Konya':'Konya',
	'Kütahya':'Kütahya',
	'Malatya':'Malatya',
	'Manisa':'Manisa',
	'K.maraş':'K.maraş',
	'Mardin':'Mardin',
	'Muğla':'Muğla',
	'Muş':'Muş',
	'Nevşehir':'Nevşehir',
	'Niğde':'Niğde',
	'Ordu':'Ordu',
	'Rize':'Rize',
	'Sakarya':'Sakarya',
	'Samsun':'Samsun',
	'Siirt':'Siirt',
	'Sinop':'Sinop',
	'Sivas':'Sivas',
	'Tekirdağ':'Tekirdağ',
	'Tokat':'Tokat',
	'Trabzon':'Trabzon',
	'Tunceli':'Tunceli',
	'Şanlıurfa':'Şanlıurfa',
	'Uşak':'Uşak',
	'Van':'Van',
	'Yozgat':'Yozgat',
	'Zonguldak':'Zonguldak',
	'Aksaray':'Aksaray',
	'Bayburt':'Bayburt',
	'Karaman':'Karaman',
	'Kırıkkale':'Kırıkkale',
	'Batman':'Batman',
	'Şırnak':'Şırnak',
	'Bartın':'Bartın',
	'Ardahan':'Ardahan',
	'Iğdır':'Iğdır',
	'Yalova':'Yalova',
	'Karabük':'Karabük',
	'Kilis':'Kilis',
	'Osmaniye':'Osmaniye',
	'Düzce':'Düzce',
}

price_choices = {
  '100000':'100,000 ₺',
  '200000':'200,000 ₺',
  '300000':'300,000 ₺',
  '400000':'400,000 ₺',
  '500000':'500,000 ₺',
  '600000':'600,000 ₺',
  '700000':'700,000 ₺',
  '800000':'800,000 ₺',
  '900000':'900,000 ₺',
  '1000000':'$1M+',
}