# Generated by Django 2.1.2 on 2018-10-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('is_mvp', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
