# Generated by Django 2.1.2 on 2018-10-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtors', '0002_realtor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='realtor',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='realtors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
