# Generated by Django 2.1.2 on 2018-10-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtor', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('product_age', models.FloatField()),
                ('photo_main', models.ImageField(upload_to='')),
                ('photo_1', models.ImageField(upload_to='')),
                ('photo_2', models.ImageField(upload_to='')),
                ('photo_3', models.ImageField(upload_to='')),
                ('photo_4', models.ImageField(upload_to='')),
                ('photo_5', models.ImageField(blank=True, upload_to='')),
                ('photo_6', models.ImageField(blank=True, upload_to='')),
                ('photo_7', models.ImageField(blank=True, upload_to='')),
                ('photo_8', models.ImageField(blank=True, upload_to='')),
                ('photo_9', models.ImageField(blank=True, upload_to='')),
                ('photo_10', models.ImageField(blank=True, upload_to='')),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
