# Generated by Django 2.1.2 on 2018-10-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realtor', to='realtors.Realtor'),
        ),
    ]
